var testPatientResource = {
	"resourceType": "Patient",
	"id": "6f0dafdc-94c5-4ab2-9208-b2872450737a",
	"meta": {
		"versionId": "2",
		"lastUpdated": "2018-10-04T15:01:18.865-04:00",
		"profile": [
			"http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-PersonOfRecord"
		],
		"tag": [{
				"system": "https://smarthealthit.org/tags",
				"code": "synthea-7-2017"
			}
		]
	},
	"text": {
		"status": "generated",
		"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>. Version identifier: 1a8d765a5375bf72f3b7a92001940d05a6f21189</div>"
	},
	"extension": [{
			"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
			"valueCodeableConcept": {
				"coding": [{
						"system": "http://hl7.org/fhir/v3/Race",
						"code": "2106-3",
						"display": "White"
					}
				],
				"text": "race"
			}
		}, {
			"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
			"valueCodeableConcept": {
				"coding": [{
						"system": "http://hl7.org/fhir/v3/Ethnicity",
						"code": "2186-5",
						"display": "Nonhispanic"
					}
				],
				"text": "ethnicity"
			}
		}, {
			"url": "http://hl7.org/fhir/StructureDefinition/birthPlace",
			"valueAddress": {
				"city": "Southborough",
				"state": "MA",
				"country": "US"
			}
		}, {
			"url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
			"valueString": "Angila Bergnaum"
		}, {
			"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
			"valueCode": "F"
		}, {
			"url": "http://hl7.org/fhir/StructureDefinition/patient-interpreterRequired",
			"valueBoolean": false
		}, {
			"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-actor-FictionalPerson-extension",
			"valueBoolean": true
		}, {
			"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-FathersName-extension",
			"valueHumanName": {
				"text": "Abram Bradtke"
			}
		}, {
			"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-SocialSecurityNumber-extension",
			"valueString": "999-50-1089"
		}
	],
	"identifier": [{
			"system": "https://github.com/synthetichealth/synthea",
			"value": "11eab7ea-963a-48ee-8a4f-ca789862f858"
		}, {
			"type": {
				"coding": [{
						"system": "http://hl7.org/fhir/identifier-type",
						"code": "SB"
					}
				]
			},
			"system": "http://hl7.org/fhir/sid/us-ssn",
			"value": "999501089"
		}, {
			"type": {
				"coding": [{
						"system": "http://hl7.org/fhir/v2/0203",
						"code": "MR"
					}
				]
			},
			"system": "http://hospital.smarthealthit.org",
			"value": "11eab7ea-963a-48ee-8a4f-ca789862f858"
		}
	],
	"name": [{
			"use": "official",
			"family": "Bradtke",
			"given": [
				"Jae"
			]
		}
	],
	"telecom": [{
			"system": "phone",
			"value": "(666) 277-8709",
			"use": "home"
		}
	],
	"gender": "female",
	"birthDate": "2008-06-19",
	"address": [{
			"extension": [{
					"url": "http://hl7.org/fhir/StructureDefinition/geolocation",
					"extension": [{
							"url": "latitude",
							"valueDecimal": 42.25870933376908
						}, {
							"url": "longitude",
							"valueDecimal": -71.61406861897434
						}
					]
				}
			],
			"line": [
				"18804 Albertha Light"
			],
			"city": "Westborough",
			"state": "MA",
			"postalCode": "01581",
			"country": "US"
		}
	],
	"maritalStatus": {
		"coding": [{
				"system": "http://hl7.org/fhir/v3/MaritalStatus",
				"code": "S"
			}
		],
		"text": "Never Married"
	},
	"multipleBirthBoolean": false,
	"contact": [{
			"relationship": [{
					"coding": [{
							"system": "http://terminology.hl7.org/CodeSystem/v2-0131",
							"code": "N"
						}
					]
				}
			],
			"name": {
				"family": "Bradtke",
				"_family": {
					"extension": [{
							"url": "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix",
							"valueString": "VV"
						}
					]
				},
				"given": [
					"Sarah"
				]
			},
			"telecom": [{
					"system": "phone",
					"value": "(237) 998-1327"
				}
			],
			"address": {
				"use": "home",
				"type": "both",
				"line": [
					"534 Erewhon St"
				],
				"city": "PleasantVille",
				"district": "Rainbow",
				"state": "Vic",
				"postalCode": "3999",
				"period": {
					"start": "1974-12-25"
				}
			},
			"gender": "female",
			"period": {
				"start": "2012"
			}
		}
	],
	"communication": [{
			"language": {
				"coding": [{
						"system": "http://hl7.org/fhir/ValueSet/languages",
						"code": "en-US",
						"display": "English (United States)"
					}
				]
			}
		}
	],
	"generalPractitioner": [{
			"reference": "Practitioner/3144"
		}
	],
	"managingOrganization": {
		"reference": "Organization/cf-1558983746326"
	}
}

var testPractitioner = {
	"resourceType": "Practitioner",
	"id": "3144",
	"meta": {
		"versionId": "1",
		"lastUpdated": "2018-09-30T17:50:38.521+00:00"
	},
	"text": {
		"status": "generated",
		"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n      <p>Dr Peter Practitioner is a Referring Practitioner for Eden Medical Center from 1-Jan 2012 to 31-Mar\n        2018</p>\n    </div>"
	},
	"identifier": [{
			"system": "http://www.acme.org/practitioners",
			"value": "23"
		}
	],
	"active": true,
	"name": [{
			"family": "Practitioner",
			"given": [
				"Peter"
			],
			"prefix": [
				"Dr"
			]
		}
	],
	"address": [{
			"use": "home",
			"line": [
				"534 Erewhon St"
			],
			"city": "PleasantVille",
			"state": "Vic",
			"postalCode": "3999"
		}
	],
	"qualification": [{
			"identifier": [{
					"system": "http://example.org/UniversityIdentifier",
					"value": "12345"
				}
			],
			"code": {
				"coding": [{
						"system": "http://hl7.org/fhir/v2/0360/2.7",
						"code": "BS",
						"display": "Bachelor of Science"
					}
				],
				"text": "Bachelor of Science"
			},
			"period": {
				"start": "1995"
			},
			"issuer": {
				"display": "Example University"
			}
		}
	]
}

var testOrganization = {
	"resourceType": "Organization",
	"id": "cf-1558983746326",
	"meta": {
		"versionId": "1",
		"lastUpdated": "2019-05-27T21:13:12.541+00:00",
		"profile": [
			" http://fhirtest.uhn.ca/baseR4/StructureDefinition/Fabricante"
		]
	},
	"implicitRules": "isLogicalModel",
	"text": {
		"status": "generated",
		"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><a name=\"mm\"></a></div>"
	},
	"extension": [{
			"url": "http://clinfhir.com/fhir/StructureDefinition/baseTypeForModel",
			"valueString": "Organization"
		}
	],
	"type": [{
			"coding": [{
					"system": "http://terminology.hl7.org/CodeSystem/organization-type",
					"code": "prov",
					"display": "Healthcare Provider"
				}
			]
		}
	],
	"name": "DR. REDDYS"
}

var testConsent = {
	"resourceType": "Consent",
	"id": "17800",
	"meta": {
		"versionId": "1",
		"lastUpdated": "2019-05-21T15:13:19.589+00:00",
		"security": [{
				"system": "2.16.840.1.113883.5.25",
				"code": "N",
				"display": "normal"
			}
		]
	},
	"text": {
		"status": "empty",
		"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Creates a policy with 1 CD: deny access to 2 organizations. The policy is activated.</div>"
	},
	"contained": [{
			"resourceType": "Patient",
			"id": "TEST-PATIENT-ID"
		}
	],
	"status": "active",
	"scope": {
		"coding": [{
				"system": "http://terminology.hl7.org/CodeSystem/consentscope",
				"code": "patient-privacy",
				"display": "Advance Care"
			}
		]
	},
	"category": [{
			"coding": [{
					"system": "http://loinc.org",
					"code": "59284-0",
					"display": "Consent Document"
				}
			]
		}
	],
	"patient": {
		"reference": "#TEST-PATIENT-ID"
	},
	"dateTime": "2019-05-21T08:08:46-04:00",
	"policy": [{
			"uri": "dummy"
		}
	],
	"provision": {
		"type": "deny",
		"period": {
			"start": "2019-05-21T11:08:46-04:00",
			"end": "2999-12-31T00:00:00-05:00"
		},
		"actor": [{
				"role": {
					"coding": [{
							"system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
							"code": "CST",
							"display": "custodian"
						}
					]
				},
				"reference": {
					"reference": "Organization/4144"
				}
			}, {
				"role": {
					"coding": [{
							"system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
							"code": "CST",
							"display": "custodian"
						}
					]
				},
				"reference": {
					"reference": "Organization/4144"
				}
			}
		],
		"action": [{
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/consentaction",
						"code": "disclose",
						"display": "Disclose"
					}
				]
			}
		]
	}
}

var testCoverage = {
	"resourceType": "Coverage",
	"id": "13917",
	"meta": {
		"versionId": "1",
		"lastUpdated": "2019-03-28T21:46:25.190+00:00"
	},
	"text": {
		"status": "generated",
		"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">A human-readable rendering of the coverage</div>"
	},
	"identifier": [{
			"system": "http://benefitsinc.com/certificate",
			"value": "12345"
		}
	],
	"status": "active",
	"type": {
		"coding": [{
				"system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
				"code": "EHCPOL",
				"display": "extended healthcare"
			}
		]
	},
	"policyHolder": {
		"reference": "http://benefitsinc.com/FHIR/Organization/CBI35"
	},
	"subscriber": {
		"reference": "Patient/3139"
	},
	"beneficiary": {
		"reference": "Patient/3139"
	},
	"dependent": "0",
	"relationship": {
		"coding": [{
				"code": "self"
			}
		]
	},
	"period": {
		"start": "2011-05-23",
		"end": "2012-05-23"
	},
	"class": [{
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "group"
					}
				]
			},
			"value": "CB135",
			"name": "Corporate Baker's Inc. Local #35"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "subgroup"
					}
				]
			},
			"value": "123",
			"name": "Trainee Part-time Benefits"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "plan"
					}
				]
			},
			"value": "B37FC",
			"name": "Full Coverage: Medical, Dental, Pharmacy, Vision, EHC"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "subplan"
					}
				]
			},
			"value": "P7",
			"name": "Includes afterlife benefits"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "class"
					}
				]
			},
			"value": "SILVER",
			"name": "Silver: Family Plan spouse only"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "subclass"
					}
				]
			},
			"value": "Tier2",
			"name": "Low deductable, max $20 copay"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "sequence"
					}
				]
			},
			"value": "9"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "rxid"
					}
				]
			},
			"value": "MDF12345"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "rxbin"
					}
				]
			},
			"value": "987654"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "rxgroup"
					}
				]
			},
			"value": "M35PT"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "rxpcn"
					}
				]
			},
			"value": "234516"
		}, {
			"type": {
				"coding": [{
						"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
						"code": "sequence"
					}
				]
			},
			"value": "9"
		}
	]
}

var testDiagnosticRpt = {
	"resourceType": "DiagnosticReport",
	"id": "55734",
	"meta": {
		"versionId": "1",
		"lastUpdated": "2019-07-08T20:50:30.415+00:00"
	},
	"text": {
		"status": "generated",
		"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><div class=\"hapiHeaderText\"> Complete blood count (hemogram) panel - Blood by Automated count </div><table class=\"hapiPropertyTable\"><tbody><tr><td>Status</td><td>FINAL</td></tr><tr><td>Issued</td><td> 13 September 2018 06:47:05</td></tr></tbody></table></div>"
	},
	"status": "final",
	"category": [{
			"coding": [{
					"system": "http://terminology.hl7.org/CodeSystem/v2-0074",
					"code": "LAB",
					"display": "Laboratory"
				}
			]
		}
	],
	"code": {
		"coding": [{
				"system": "http://loinc.org",
				"code": "58410-2",
				"display": "Complete blood count (hemogram) panel - Blood by Automated count"
			}
		],
		"text": "Complete blood count (hemogram) panel - Blood by Automated count"
	},
	"subject": {
		"reference": "Patient/55708"
	},
	"encounter": {
		"reference": "Encounter/55711"
	},
	"effectiveDateTime": "2018-09-13T08:47:05+02:00",
	"issued": "2018-09-13T08:47:05.127+02:00",
	"result": [{
			"reference": "Observation/55717",
			"display": "Leukocytes [#/volume] in Blood by Automated count"
		}, {
			"reference": "Observation/55718",
			"display": "Erythrocytes [#/volume] in Blood by Automated count"
		}, {
			"reference": "Observation/55719",
			"display": "Hemoglobin [Mass/volume] in Blood"
		}, {
			"reference": "Observation/55720",
			"display": "Hematocrit [Volume Fraction] of Blood by Automated count"
		}, {
			"reference": "Observation/55721",
			"display": "MCV [Entitic volume] by Automated count"
		}, {
			"reference": "Observation/55722",
			"display": "MCH [Entitic mass] by Automated count"
		}, {
			"reference": "Observation/55723",
			"display": "MCHC [Mass/volume] by Automated count"
		}, {
			"reference": "Observation/55724",
			"display": "Erythrocyte distribution width [Entitic volume] by Automated count"
		}, {
			"reference": "Observation/55725",
			"display": "Platelets [#/volume] in Blood by Automated count"
		}, {
			"reference": "Observation/55726",
			"display": "Platelet distribution width [Entitic volume] in Blood by Automated count"
		}, {
			"reference": "Observation/55727",
			"display": "Platelet mean volume [Entitic volume] in Blood by Automated count"
		}
	]
}

var testBatch = {
	"resourceType": "Bundle",
	"id": "2b55b88a-8f7a-423c-abf5-4a7242378271",
	"meta": {
		"lastUpdated": "2019-10-04T11:34:25.950-04:00"
	},
	"type": "searchset",
	"total": 1,
	"link": [{
			"relation": "self",
			"url": "https://r3.smarthealthit.org/Patient?_id=6f0dafdc-94c5-4ab2-9208-b2872450737a&_revinclude=Condition%3Asubject&_revinclude=AllergyIntolerance%3Apatient&_revinclude=MedicationRequest%3Asubject"
		}
	],
	"entry": [{
			"fullUrl": "https://r3.smarthealthit.org/Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a",
			"resource": {
				"resourceType": "Patient",
				"id": "6f0dafdc-94c5-4ab2-9208-b2872450737a",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T02:41:53.794-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-PersonOfRecord"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"text": {
					"status": "generated",
					"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>. Version identifier: 1a8d765a5375bf72f3b7a92001940d05a6f21189</div>"
				},
				"extension": [{
						"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
						"valueCodeableConcept": {
							"coding": [{
									"system": "http://hl7.org/fhir/v3/Race",
									"code": "2106-3",
									"display": "White"
								}
							],
							"text": "race"
						}
					}, {
						"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
						"valueCodeableConcept": {
							"coding": [{
									"system": "http://hl7.org/fhir/v3/Ethnicity",
									"code": "2186-5",
									"display": "Nonhispanic"
								}
							],
							"text": "ethnicity"
						}
					}, {
						"url": "http://hl7.org/fhir/StructureDefinition/birthPlace",
						"valueAddress": {
							"city": "Southborough",
							"state": "MA",
							"country": "US"
						}
					}, {
						"url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
						"valueString": "Angila Bergnaum"
					}, {
						"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
						"valueCode": "F"
					}, {
						"url": "http://hl7.org/fhir/StructureDefinition/patient-interpreterRequired",
						"valueBoolean": false
					}, {
						"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-actor-FictionalPerson-extension",
						"valueBoolean": true
					}, {
						"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-FathersName-extension",
						"valueHumanName": {
							"text": "Abram Bradtke"
						}
					}, {
						"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-SocialSecurityNumber-extension",
						"valueString": "999-50-1089"
					}
				],
				"identifier": [{
						"system": "https://github.com/synthetichealth/synthea",
						"value": "11eab7ea-963a-48ee-8a4f-ca789862f858"
					}, {
						"type": {
							"coding": [{
									"system": "http://hl7.org/fhir/identifier-type",
									"code": "SB"
								}
							]
						},
						"system": "http://hl7.org/fhir/sid/us-ssn",
						"value": "999501089"
					}, {
						"type": {
							"coding": [{
									"system": "http://hl7.org/fhir/v2/0203",
									"code": "MR"
								}
							]
						},
						"system": "http://hospital.smarthealthit.org",
						"value": "11eab7ea-963a-48ee-8a4f-ca789862f858"
					}
				],
				"name": [{
						"use": "official",
						"family": "Bradtke",
						"given": [
							"Jae"
						]
					}
				],
				"telecom": [{
						"system": "phone",
						"value": "(666) 277-8709",
						"use": "home"
					}
				],
				"gender": "female",
				"birthDate": "2008-06-19",
				"address": [{
						"extension": [{
								"url": "http://hl7.org/fhir/StructureDefinition/geolocation",
								"extension": [{
										"url": "latitude",
										"valueDecimal": 42.25870933376908
									}, {
										"url": "longitude",
										"valueDecimal": -71.61406861897434
									}
								]
							}
						],
						"line": [
							"18804 Albertha Light"
						],
						"city": "Westborough",
						"state": "MA",
						"postalCode": "01581",
						"country": "US"
					}
				],
				"maritalStatus": {
					"coding": [{
							"system": "http://hl7.org/fhir/v3/MaritalStatus",
							"code": "S"
						}
					],
					"text": "Never Married"
				},
				"multipleBirthBoolean": false,
				"contact": [{
						"relationship": [{
								"coding": [{
										"system": "http://terminology.hl7.org/CodeSystem/v2-0131",
										"code": "N"
									}
								],
								"text": "Next of Kin"
							}
						],
						"name": {
							"family": "Bradtke",
							"_family": {
								"extension": [{
										"url": "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix",
										"valueString": "VV"
									}
								]
							},
							"given": [
								"Sarah"
							]
						},
						"telecom": [{
								"system": "phone",
								"value": "(237) 998-1327"
							}
						],
						"address": {
							"use": "home",
							"type": "both",
							"line": [
								"534 Erewhon St"
							],
							"city": "PleasantVille",
							"district": "Rainbow",
							"state": "Vic",
							"postalCode": "3999",
							"period": {
								"start": "1974-12-25"
							}
						},
						"gender": "female",
						"period": {
							"start": "2012"
						}
					}
				],
				"communication": [{
						"language": {
							"coding": [{
									"system": "http://hl7.org/fhir/ValueSet/languages",
									"code": "en-US",
									"display": "English (United States)"
								}
							]
						}
					}
				]
			},
			"search": {
				"mode": "match"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/MedicationRequest/11ba2624-e7fe-4547-9681-d90eb50d9aea",
			"resource": {
				"resourceType": "MedicationRequest",
				"id": "11ba2624-e7fe-4547-9681-d90eb50d9aea",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2018-04-30T13:29:50.226-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-medication-MedicationPrescription"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"extension": [{
						"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-base-ActionCode-extension",
						"valueCodeableConcept": {
							"coding": [{
									"system": "http://snomed.info/sct",
									"code": "33633005",
									"display": "Prescription of drug (procedure)"
								}
							],
							"text": "Prescription of drug (procedure)"
						}
					}
				],
				"status": "stopped",
				"intent": "order",
				"medicationReference": {
					"reference": "Medication/6e3212df-8ba8-42c9-b41f-363d24c989f7"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/6b9dcf3c-a7fe-4110-999b-59df0f48f6d4"
				},
				"authoredOn": "2012-11-26",
				"dosageInstruction": [{
						"sequence": 1,
						"asNeededBoolean": true
					}
				]
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/Condition/0ad8c538-8ff1-4ac7-875c-d857517616fe",
			"resource": {
				"resourceType": "Condition",
				"id": "0ad8c538-8ff1-4ac7-875c-d857517616fe",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:03:53.699-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-problem-Problem"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"clinicalStatus": "active",
				"verificationStatus": "confirmed",
				"code": {
					"coding": [{
							"system": "http://snomed.info/sct",
							"code": "444814009",
							"display": "Viral sinusitis (disorder)"
						}
					],
					"text": "Viral sinusitis (disorder)"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/59c69683-826b-4715-8363-f288ee2c46b3"
				},
				"onsetDateTime": "2015-09-02T14:34:47-04:00",
				"abatementDateTime": "2015-09-30T06:59:52-04:00",
				"assertedDate": "2015-09-02"
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/MedicationRequest/327244f1-0f4b-4559-9b6e-e0b7f99ec607",
			"resource": {
				"resourceType": "MedicationRequest",
				"id": "327244f1-0f4b-4559-9b6e-e0b7f99ec607",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2018-04-30T13:26:01.351-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-medication-MedicationPrescription"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"extension": [{
						"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-base-ActionCode-extension",
						"valueCodeableConcept": {
							"coding": [{
									"system": "http://snomed.info/sct",
									"code": "33633005",
									"display": "Prescription of drug (procedure)"
								}
							],
							"text": "Prescription of drug (procedure)"
						}
					}
				],
				"status": "stopped",
				"intent": "order",
				"medicationReference": {
					"reference": "Medication/7c91660f-f31f-4573-9f48-bfe8ade9b003"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/2a82ffa3-bfbc-49f2-bbaf-4ab50e68ab3b"
				},
				"authoredOn": "2009-12-28",
				"reasonReference": [{
						"reference": "Condition/18f82b52-68a3-4571-9ce0-481c23e231e6"
					}
				]
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/AllergyIntolerance/RES157368",
			"resource": {
				"resourceType": "AllergyIntolerance",
				"id": "RES157368",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2018-10-05T02:44:23.605-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-allergy-AllergyIntolerance"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"clinicalStatus": "active",
				"verificationStatus": "confirmed",
				"type": "allergy",
				"category": [
					"food"
				],
				"criticality": "low",
				"code": {
					"coding": [{
							"system": "http://snomed.info/sct",
							"code": "417532002",
							"display": "Allergy to fish"
						}
					]
				},
				"patient": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"assertedDate": "2009-12-15T14:36:09-05:00"
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/Condition/25d3f739-e8b1-466b-9525-623da419c97d",
			"resource": {
				"resourceType": "Condition",
				"id": "25d3f739-e8b1-466b-9525-623da419c97d",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:11:14.035-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-problem-Problem"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"clinicalStatus": "active",
				"verificationStatus": "confirmed",
				"code": {
					"coding": [{
							"system": "http://snomed.info/sct",
							"code": "65363002",
							"display": "Otitis media"
						}
					],
					"text": "Otitis media"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/6b9dcf3c-a7fe-4110-999b-59df0f48f6d4"
				},
				"onsetDateTime": "2012-11-26T15:30:59-05:00",
				"abatementDateTime": "2013-11-12T04:41:02-05:00",
				"assertedDate": "2012-11-26"
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/MedicationRequest/3f6f7567-2d4d-46d1-9952-21985907d520",
			"resource": {
				"resourceType": "MedicationRequest",
				"id": "3f6f7567-2d4d-46d1-9952-21985907d520",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2018-04-30T13:32:46.342-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-medication-MedicationPrescription"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"extension": [{
						"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-base-ActionCode-extension",
						"valueCodeableConcept": {
							"coding": [{
									"system": "http://snomed.info/sct",
									"code": "33633005",
									"display": "Prescription of drug (procedure)"
								}
							],
							"text": "Prescription of drug (procedure)"
						}
					}
				],
				"status": "active",
				"intent": "order",
				"medicationReference": {
					"reference": "Medication/96827cbc-f276-48ae-a874-f7682af85952"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/1e7b158f-c817-4572-a621-4c372d6711f2"
				},
				"authoredOn": "2009-12-15",
				"dosageInstruction": [{
						"sequence": 1,
						"asNeededBoolean": true
					}
				]
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/MedicationRequest/c41acc5e-f5b4-4d02-8a9e-75d17f1e932a",
			"resource": {
				"resourceType": "MedicationRequest",
				"id": "c41acc5e-f5b4-4d02-8a9e-75d17f1e932a",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2018-04-30T13:34:06.371-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-medication-MedicationPrescription"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"extension": [{
						"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-base-ActionCode-extension",
						"valueCodeableConcept": {
							"coding": [{
									"system": "http://snomed.info/sct",
									"code": "33633005",
									"display": "Prescription of drug (procedure)"
								}
							],
							"text": "Prescription of drug (procedure)"
						}
					}
				],
				"status": "stopped",
				"intent": "order",
				"medicationReference": {
					"reference": "Medication/444a5cf0-d9ba-4fdf-acf1-7a0c92c7ca50"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/6b9dcf3c-a7fe-4110-999b-59df0f48f6d4"
				},
				"authoredOn": "2012-11-26",
				"dosageInstruction": [{
						"sequence": 1,
						"additionalInstruction": [{
								"coding": [{
										"system": "http://snomed.info/sct",
										"code": "418577003",
										"display": "Take at regular intervals. Complete the prescribed course unless otherwise directed."
									}
								]
							}
						],
						"timing": {
							"repeat": {
								"frequency": 2,
								"period": 1,
								"periodUnit": "d"
							}
						},
						"asNeededBoolean": false,
						"doseQuantity": {
							"value": 1
						}
					}
				],
				"dispenseRequest": {
					"numberOfRepeatsAllowed": 0,
					"quantity": {
						"value": 28,
						"unit": "doses"
					},
					"expectedSupplyDuration": {
						"value": 2,
						"unit": "weeks",
						"system": "http://unitsofmeasure.org",
						"code": "wk"
					}
				}
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/AllergyIntolerance/RES34061",
			"resource": {
				"resourceType": "AllergyIntolerance",
				"id": "RES34061",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:14:35.351-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-allergy-AllergyIntolerance"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"clinicalStatus": "active",
				"verificationStatus": "confirmed",
				"type": "allergy",
				"category": [
					"food"
				],
				"criticality": "low",
				"code": {
					"coding": [{
							"system": "http://snomed.info/sct",
							"code": "417532002",
							"display": "Allergy to fish"
						}
					]
				},
				"patient": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"assertedDate": "2009-12-15T14:36:09-05:00"
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/Condition/18f82b52-68a3-4571-9ce0-481c23e231e6",
			"resource": {
				"resourceType": "Condition",
				"id": "18f82b52-68a3-4571-9ce0-481c23e231e6",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:04:50.037-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-problem-Problem"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"clinicalStatus": "active",
				"verificationStatus": "confirmed",
				"code": {
					"coding": [{
							"system": "http://snomed.info/sct",
							"code": "10509002",
							"display": "Acute bronchitis (disorder)"
						}
					],
					"text": "Acute bronchitis (disorder)"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/2a82ffa3-bfbc-49f2-bbaf-4ab50e68ab3b"
				},
				"onsetDateTime": "2009-12-28T12:58:02-05:00",
				"abatementDateTime": "2010-01-12T08:34:12-05:00",
				"assertedDate": "2009-12-28"
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/Condition/bcc15d98-9ed4-4891-86e6-fb7437e8d5b6",
			"resource": {
				"resourceType": "Condition",
				"id": "bcc15d98-9ed4-4891-86e6-fb7437e8d5b6",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:06:01.194-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-problem-Problem"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"clinicalStatus": "active",
				"verificationStatus": "confirmed",
				"code": {
					"coding": [{
							"system": "http://snomed.info/sct",
							"code": "10509002",
							"display": "Acute bronchitis (disorder)"
						}
					],
					"text": "Acute bronchitis (disorder)"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/b520f797-0812-4b1d-821c-90780daf9249"
				},
				"onsetDateTime": "2012-09-20T07:40:37-04:00",
				"abatementDateTime": "2012-10-01T01:56:50-04:00",
				"assertedDate": "2012-09-20"
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/Condition/90fa7acb-762d-4e9d-92e1-6329ef0701d9",
			"resource": {
				"resourceType": "Condition",
				"id": "90fa7acb-762d-4e9d-92e1-6329ef0701d9",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:01:13.032-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-problem-Problem"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"clinicalStatus": "active",
				"verificationStatus": "confirmed",
				"code": {
					"coding": [{
							"system": "http://snomed.info/sct",
							"code": "192127007",
							"display": "Child attention deficit disorder"
						}
					],
					"text": "Child attention deficit disorder"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/4e5c9f29-2c42-4aae-b636-3e2bdb168ede"
				},
				"onsetDateTime": "2016-10-24T11:08:51-04:00",
				"assertedDate": "2016-10-24"
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/Condition/7e3baa81-7b16-4eda-a686-6e27531d51b4",
			"resource": {
				"resourceType": "Condition",
				"id": "7e3baa81-7b16-4eda-a686-6e27531d51b4",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T02:57:03.394-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-problem-Problem"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"clinicalStatus": "active",
				"verificationStatus": "confirmed",
				"code": {
					"coding": [{
							"system": "http://snomed.info/sct",
							"code": "195662009",
							"display": "Acute viral pharyngitis (disorder)"
						}
					],
					"text": "Acute viral pharyngitis (disorder)"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/b1d000d5-df60-438c-83c8-49b83800defd"
				},
				"onsetDateTime": "2013-05-28T06:10:55-04:00",
				"abatementDateTime": "2013-06-04T20:25:55-04:00",
				"assertedDate": "2013-05-28"
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/MedicationRequest/860f8027-1c9b-42f7-979d-48cb5fbd9de4",
			"resource": {
				"resourceType": "MedicationRequest",
				"id": "860f8027-1c9b-42f7-979d-48cb5fbd9de4",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2018-04-30T13:34:56.262-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-medication-MedicationPrescription"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"extension": [{
						"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-base-ActionCode-extension",
						"valueCodeableConcept": {
							"coding": [{
									"system": "http://snomed.info/sct",
									"code": "33633005",
									"display": "Prescription of drug (procedure)"
								}
							],
							"text": "Prescription of drug (procedure)"
						}
					}
				],
				"status": "stopped",
				"intent": "order",
				"medicationReference": {
					"reference": "Medication/7c91660f-f31f-4573-9f48-bfe8ade9b003"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/b520f797-0812-4b1d-821c-90780daf9249"
				},
				"authoredOn": "2012-09-22",
				"reasonReference": [{
						"reference": "Condition/18f82b52-68a3-4571-9ce0-481c23e231e6"
					}
				]
			},
			"search": {
				"mode": "include"
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/MedicationRequest/bdce03e2-1d8f-472d-a7ad-13cc684d5f0b",
			"resource": {
				"resourceType": "MedicationRequest",
				"id": "bdce03e2-1d8f-472d-a7ad-13cc684d5f0b",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2018-04-30T13:27:46.638-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-medication-MedicationPrescription"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"extension": [{
						"url": "http://standardhealthrecord.org/fhir/StructureDefinition/shr-base-ActionCode-extension",
						"valueCodeableConcept": {
							"coding": [{
									"system": "http://snomed.info/sct",
									"code": "33633005",
									"display": "Prescription of drug (procedure)"
								}
							],
							"text": "Prescription of drug (procedure)"
						}
					}
				],
				"status": "active",
				"intent": "order",
				"medicationReference": {
					"reference": "Medication/53b047d9-b634-4088-85c0-6006f99d183a"
				},
				"subject": {
					"reference": "Patient/6f0dafdc-94c5-4ab2-9208-b2872450737a"
				},
				"context": {
					"reference": "Encounter/1e7b158f-c817-4572-a621-4c372d6711f2"
				},
				"authoredOn": "2009-12-15",
				"dosageInstruction": [{
						"sequence": 1,
						"asNeededBoolean": true
					}
				]
			},
			"search": {
				"mode": "include"
			}
		}, {
			"resource": {
				"resourceType": "Practitioner",
				"id": "3144",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2018-09-30T17:50:38.521+00:00"
				},
				"text": {
					"status": "generated",
					"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n      <p>Dr Peter Practitioner is a Referring Practitioner for Eden Medical Center from 1-Jan 2012 to 31-Mar\n        2018</p>\n    </div>"
				},
				"identifier": [{
						"system": "http://www.acme.org/practitioners",
						"value": "23"
					}
				],
				"active": true,
				"name": [{
						"family": "Practitioner",
						"given": [
							"Peter"
						],
						"prefix": [
							"Dr"
						]
					}
				],
				"telecom": [{
						"system": "phone",
						"value": "(666) 555-4444",
						"use": "home"
					}
				],
				"address": [{
						"use": "home",
						"line": [
							"534 Erewhon St"
						],
						"city": "PleasantVille",
						"state": "Vic",
						"postalCode": "3999"
					}
				],
				"gender": "male",
				"qualification": [{
						"identifier": [{
								"system": "http://example.org/UniversityIdentifier",
								"value": "12345"
							}
						],
						"code": {
							"coding": [{
									"system": "http://hl7.org/fhir/v2/0360/2.7",
									"code": "BS",
									"display": "Bachelor of Science"
								}
							],
							"text": "Bachelor of Science"
						},
						"period": {
							"start": "1995"
						},
						"issuer": {
							"display": "Example University"
						}
					}
				]
			}
		}, {
			"resource": {
				"resourceType": "Organization",
				"id": "cf-1558983746326",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2019-05-27T21:13:12.541+00:00",
					"profile": [
						" http://fhirtest.uhn.ca/baseR4/StructureDefinition/Fabricante"
					]
				},
				"implicitRules": "isLogicalModel",
				"text": {
					"status": "generated",
					"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><a name=\"mm\"></a></div>"
				},
				"extension": [{
						"url": "http://clinfhir.com/fhir/StructureDefinition/baseTypeForModel",
						"valueString": "Organization"
					}
				],
				"type": [{
						"coding": [{
								"system": "http://terminology.hl7.org/CodeSystem/organization-type",
								"code": "prov",
								"display": "Healthcare Provider"
							}
						]
					}
				],
				"name": "DR. REDDYS",
				"telecom": [{
						"system": "phone",
						"value": "(666) 277-8709",
						"use": "home"
					}
				],
				"address": [{
						"extension": [{
								"url": "http://hl7.org/fhir/StructureDefinition/geolocation",
								"extension": [{
										"url": "latitude",
										"valueDecimal": 42.25870933376908
									}, {
										"url": "longitude",
										"valueDecimal": -71.61406861897434
									}
								]
							}
						],
						"line": [
							"5555 Dead End Dr."
						],
						"city": "Mars",
						"state": "IN",
						"postalCode": "01581",
						"country": "US"
					}
				]
			}
		}, {
			"resource": {
				"resourceType": "DiagnosticReport",
				"id": "55734",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2019-07-08T20:50:30.415+00:00"
				},
				"text": {
					"status": "generated",
					"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><div class=\"hapiHeaderText\"> Complete blood count (hemogram) panel - Blood by Automated count </div><table class=\"hapiPropertyTable\"><tbody><tr><td>Status</td><td>FINAL</td></tr><tr><td>Issued</td><td> 13 September 2018 06:47:05</td></tr></tbody></table></div>"
				},
				"status": "final",
				"category": [{
						"coding": [{
								"system": "http://terminology.hl7.org/CodeSystem/v2-0074",
								"code": "LAB",
								"display": "Laboratory"
							}
						]
					}
				],
				"code": {
					"coding": [{
							"system": "http://loinc.org",
							"code": "58410-2",
							"display": "Complete blood count (hemogram) panel - Blood by Automated count"
						}
					],
					"text": "Complete blood count (hemogram) panel - Blood by Automated count"
				},
				"subject": {
					"reference": "Patient/55708"
				},
				"encounter": {
					"reference": "Encounter/55711"
				},
				"effectiveDateTime": "2018-09-13T08:47:05+02:00",
				"issued": "2018-09-13T08:47:05.127+02:00",
				"result": [{
						"reference": "Observation/55717",
						"display": "Leukocytes [#/volume] in Blood by Automated count"
					}, {
						"reference": "Observation/55718",
						"display": "Erythrocytes [#/volume] in Blood by Automated count"
					}, {
						"reference": "Observation/55719",
						"display": "Hemoglobin [Mass/volume] in Blood"
					}, {
						"reference": "Observation/55720",
						"display": "Hematocrit [Volume Fraction] of Blood by Automated count"
					}, {
						"reference": "Observation/55721",
						"display": "MCV [Entitic volume] by Automated count"
					}, {
						"reference": "Observation/55722",
						"display": "MCH [Entitic mass] by Automated count"
					}, {
						"reference": "Observation/55723",
						"display": "MCHC [Mass/volume] by Automated count"
					}, {
						"reference": "Observation/55724",
						"display": "Erythrocyte distribution width [Entitic volume] by Automated count"
					}, {
						"reference": "Observation/55725",
						"display": "Platelets [#/volume] in Blood by Automated count"
					}, {
						"reference": "Observation/55726",
						"display": "Platelet distribution width [Entitic volume] in Blood by Automated count"
					}, {
						"reference": "Observation/55727",
						"display": "Platelet mean volume [Entitic volume] in Blood by Automated count"
					}
				]
			}
		}, {
			"resource": {
				"resourceType": "Coverage",
				"id": "13917",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2019-03-28T21:46:25.190+00:00"
				},
				"text": {
					"status": "generated",
					"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">A human-readable rendering of the coverage</div>"
				},
				"identifier": [{
						"system": "http://benefitsinc.com/certificate",
						"value": "12345"
					}
				],
				"status": "active",
				"type": {
					"coding": [{
							"system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
							"code": "EHCPOL",
							"display": "extended healthcare"
						}
					]
				},
				"policyHolder": {
					"reference": "http://benefitsinc.com/FHIR/Organization/CBI35"
				},
				"subscriber": {
					"reference": "Patient/3139"
				},
				"beneficiary": {
					"reference": "Patient/3139"
				},
				"dependent": "0",
				"relationship": {
					"coding": [{
							"code": "self"
						}
					]
				},
				"period": {
					"start": "2011-05-23",
					"end": "2012-05-23"
				},
				"class": [{
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "group"
								}
							]
						},
						"value": "CB135",
						"name": "Corporate Baker's Inc. Local #35"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "subgroup"
								}
							]
						},
						"value": "123",
						"name": "Trainee Part-time Benefits"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "plan"
								}
							]
						},
						"value": "B37FC",
						"name": "Full Coverage: Medical, Dental, Pharmacy, Vision, EHC"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "subplan"
								}
							]
						},
						"value": "P7",
						"name": "Includes afterlife benefits"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "class"
								}
							]
						},
						"value": "SILVER",
						"name": "Silver: Family Plan spouse only"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "subclass"
								}
							]
						},
						"value": "Tier2",
						"name": "Low deductable, max $20 copay"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "sequence"
								}
							]
						},
						"value": "9"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "rxid"
								}
							]
						},
						"value": "MDF12345"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "rxbin"
								}
							]
						},
						"value": "987654"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "rxgroup"
								}
							]
						},
						"value": "M35PT"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "rxpcn"
								}
							]
						},
						"value": "234516"
					}, {
						"type": {
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/coverage-class",
									"code": "sequence"
								}
							]
						},
						"value": "9"
					}
				]
			}
		}, {
			"resource": {
				"resourceType": "Consent",
				"id": "17800",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2019-05-21T15:13:19.589+00:00",
					"security": [{
							"system": "2.16.840.1.113883.5.25",
							"code": "N",
							"display": "normal"
						}
					]
				},
				"text": {
					"status": "empty",
					"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Creates a policy with 1 CD: deny access to 2 organizations. The policy is activated.</div>"
				},
				"contained": [{
						"resourceType": "Patient",
						"id": "TEST-PATIENT-ID"
					}
				],
				"status": "active",
				"scope": {
					"coding": [{
							"system": "http://terminology.hl7.org/CodeSystem/consentscope",
							"code": "patient-privacy",
							"display": "Advance Care"
						}
					]
				},
				"category": [{
						"coding": [{
								"system": "http://loinc.org",
								"code": "59284-0",
								"display": "Consent Document"
							}
						]
					}
				],
				"patient": {
					"reference": "#TEST-PATIENT-ID"
				},
				"dateTime": "2019-05-21T08:08:46-04:00",
				"policy": [{
						"uri": "dummy"
					}
				],
				"provision": {
					"type": "deny",
					"period": {
						"start": "2019-05-21T11:08:46-04:00",
						"end": "2999-12-31T00:00:00-05:00"
					},
					"actor": [{
							"role": {
								"coding": [{
										"system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
										"code": "CST",
										"display": "custodian"
									}
								]
							},
							"reference": {
								"reference": "Organization/4144"
							}
						}, {
							"role": {
								"coding": [{
										"system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
										"code": "CST",
										"display": "custodian"
									}
								]
							},
							"reference": {
								"reference": "Organization/4144"
							}
						}
					],
					"action": [{
							"coding": [{
									"system": "http://terminology.hl7.org/CodeSystem/consentaction",
									"code": "disclose",
									"display": "Disclose"
								}
							]
						}
					]
				}
			}

		}, {
			"fullUrl": "https://r3.smarthealthit.org/MedicationStatement/220115",
			"resource": {
				"resourceType": "MedicationStatement",
				"id": "220115",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2019-03-17T12:24:01.013-04:00"
				},
				"status": "active",
				"medicationCodeableConcept": {
					"coding": [{
							"system": "http://www.nlm.nih.gov/research/umls/rxnorm",
							"code": "308056",
							"display": "Alteplase 1 MG/ML Injectable Solution"
						}
					],
					"text": "Alteplase 1 MG/ML Injectable Solution"
				},
				"dateAsserted": "2019-01-18",
				"subject": {
					"reference": "Patient/2c4c5104-6d23-4c0a-97e9-bd229fc3559c"
				},
				"taken": "y"
			},
			"search": {
				"mode": "match"
			}

		}, {
			"fullUrl": "https://r3.smarthealthit.org/MedicationStatement/220118",
			"resource": {
				"resourceType": "MedicationStatement",
				"id": "220118",
				"meta": {
					"versionId": "1",
					"lastUpdated": "2019-03-18T00:03:26.361-04:00"
				},
				"status": "active",
				"medicationCodeableConcept": {
					"coding": [{
							"system": "http://www.nlm.nih.gov/research/umls/rxnorm",
							"code": "308056",
							"display": "Alteplase 1 MG/ML Injectable Solution"
						}
					],
					"text": "Alteplase 1 MG/ML Injectable Solution"
				},
				"dateAsserted": "2019-03-17",
				"subject": {
					"reference": "Patient/2c4c5104-6d23-4c0a-97e9-bd229fc3559c"
				},
				"taken": "y"
			},
			"search": {
				"mode": "match"
			}

		}, {
			"fullUrl": "https://r3.smarthealthit.org/Observation/85e58b9a-7980-4a78-92a4-14f7d01d6361",
			"resource": {
				"resourceType": "Observation",
				"id": "85e58b9a-7980-4a78-92a4-14f7d01d6361",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:26:12.748-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-observation-Observation"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"status": "final",
				"category": [{
						"coding": [{
								"system": "http://hl7.org/fhir/observation-category",
								"code": "laboratory"
							}
						]
					}
				],
				"code": {
					"coding": [{
							"system": "http://loinc.org",
							"code": "33914-3",
							"display": "Estimated Glomerular Filtration Rate"
						}
					],
					"text": "Estimated Glomerular Filtration Rate"
				},
				"subject": {
					"reference": "Patient/3b5064a0-e23c-458c-897e-3491a494eb32"
				},
				"context": {
					"reference": "Encounter/04b80d1b-3456-44bc-aaae-67894d2d4c73"
				},
				"effectiveDateTime": "2017-06-04T23:57:01-04:00",
				"issued": "2017-06-04T23:57:01-04:00",
				"valueQuantity": {
					"value": 60,
					"unit": "mL/min/{1.73_m2}",
					"system": "http://unitsofmeasure.org/",
					"code": "mL/min/{1.73_m2}"
				}
			},
			"search": {
				"mode": "match"
			}

		}, {
			"fullUrl": "https://r3.smarthealthit.org/Observation/8d9f6174-9343-471a-8bc7-6e5e9cbaba43",
			"resource": {
				"resourceType": "Observation",
				"id": "8d9f6174-9343-471a-8bc7-6e5e9cbaba43",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:24:33.805-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-observation-Observation"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"status": "final",
				"category": [{
						"coding": [{
								"system": "http://hl7.org/fhir/observation-category",
								"code": "laboratory"
							}
						]
					}
				],
				"code": {
					"coding": [{
							"system": "http://loinc.org",
							"code": "4548-4",
							"display": "Hemoglobin A1c/Hemoglobin.total in Blood"
						}
					],
					"text": "Hemoglobin A1c/Hemoglobin.total in Blood"
				},
				"subject": {
					"reference": "Patient/3b5064a0-e23c-458c-897e-3491a494eb32"
				},
				"context": {
					"reference": "Encounter/b1d74bf2-6d2e-4f59-8321-6ad910bb232c"
				},
				"effectiveDateTime": "2011-07-10T07:30:21-04:00",
				"issued": "2011-07-10T07:30:21-04:00",
				"valueQuantity": {
					"value": 6,
					"unit": "%",
					"system": "http://unitsofmeasure.org/",
					"code": "%"
				}
			},
			"search": {
				"mode": "match"
			}

		}, {
			"resource": {
			"resourceType": "Observation",
			"id": "48772",
			"meta": {
				"versionId": "1",
				"lastUpdated": "2019-10-18T11:43:14.079+00:00",
				"source": "#CY1Q7e2BKq8LvVzx"
			},
			"status": "final",
			"category": [{
					"coding": [{
							"system": "http://terminology.hl7.org/CodeSystem/observation-category",
							"code": "vital-signs",
							"display": "vital-signs"
						}
					],
					"text": "vital-signs"
				}
			],
			"code": {
				"coding": [{
						"code": "vital-signs"
					}
				]
			},
			"subject": {
				"reference": "Patient/48761",
				"type": "Patient",
				"display": "Avaz Alimov"
			},
			"issued": "2019-10-18T11:43:13.706Z",
			"performer": [{
					"reference": "Practitioner/48757",
					"type": "Practitioner",
					"display": "Avaz Alimov"
				}
			],
			"component": [{
					"code": {
						"coding": [{
								"system": "http://loinc.org",
								"code": "8867-4",
								"display": "Heart rate"
							}
						]
					},
					"valueString": "10"
				}, {
					"code": {
						"coding": [{
								"system": "http://loinc.org",
								"code": "8310-5",
								"display": "Body temperature"
							}
						]
					},
					"valueString": "10"
				}, {
					"code": {
						"coding": [{
								"system": "http://loinc.org",
								"code": "20564-1",
								"display": "Oxygen saturation in Blood"
							}
						]
					},
					"valueString": "10"
				}, {
					"code": {
						"coding": [{
								"system": "http://loinc.org",
								"code": "29463-7",
								"display": "Body weight"
							}
						]
					},
					"valueString": "10"
				}, {
					"code": {
						"coding": [{
								"system": "http://loinc.org",
								"code": "8302-2",
								"display": "Body height"
							}
						]
					},
					"valueString": "10"
				}, {
					"code": {
						"coding": [{
								"system": "http://loinc.org",
								"code": "2339-0",
								"display": "Glucose [Mass/volume] in Blood"
							}
						]
					},
					"valueString": "10"
				}, {
					"code": {
						"coding": [{
								"system": "http://loinc.org",
								"code": "8462-4",
								"display": "Diastolic blood pressure"
							}
						]
					},
					"valueString": "10"
				}, {
					"code": {
						"coding": [{
								"system": "http://loinc.org",
								"code": "8480-6",
								"display": "Systolic blood pressure"
							}
						]
					},
					"valueString": "10"
				}
			]
			}
		}, {
			"fullUrl": "https://r3.smarthealthit.org/Observation/371a039c-4b03-423c-8b9d-685ca7c2cd43",
			"resource": {
				"resourceType": "Observation",
				"id": "371a039c-4b03-423c-8b9d-685ca7c2cd43",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:24:14.378-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-observation-Observation"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"status": "final",
				"category": [{
						"coding": [{
								"system": "http://hl7.org/fhir/observation-category",
								"code": "laboratory"
							}
						]
					}
				],
				"code": {
					"coding": [{
							"system": "http://loinc.org",
							"code": "6298-4",
							"display": "Potassium"
						}
					],
					"text": "Potassium"
				},
				"subject": {
					"reference": "Patient/3b5064a0-e23c-458c-897e-3491a494eb32"
				},
				"context": {
					"reference": "Encounter/b1d74bf2-6d2e-4f59-8321-6ad910bb232c"
				},
				"effectiveDateTime": "2011-07-10T07:30:21-04:00",
				"issued": "2011-07-10T07:30:21-04:00",
				"valueQuantity": {
					"value": 4.96,
					"unit": "mmol/L",
					"system": "http://unitsofmeasure.org/",
					"code": "mmol/L"
				}
			},
			"search": {
				"mode": "match"
			}

		}, {
			"fullUrl": "https://r3.smarthealthit.org/Observation/75e0a52d-24ce-4461-9f75-695ab71cf409",
			"resource": {
				"resourceType": "Observation",
				"id": "75e0a52d-24ce-4461-9f75-695ab71cf409",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:23:31.137-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-observation-Observation"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"status": "final",
				"category": [{
						"coding": [{
								"system": "http://hl7.org/fhir/observation-category",
								"code": "laboratory"
							}
						]
					}
				],
				"code": {
					"coding": [{
							"system": "http://loinc.org",
							"code": "20565-8",
							"display": "Carbon Dioxide"
						}
					],
					"text": "Carbon Dioxide"
				},
				"subject": {
					"reference": "Patient/3b5064a0-e23c-458c-897e-3491a494eb32"
				},
				"context": {
					"reference": "Encounter/cf5ba549-78b8-4f93-b9b5-1d5f73f6a6d1"
				},
				"effectiveDateTime": "2008-03-07T23:13:53-05:00",
				"issued": "2008-03-07T23:13:53-05:00",
				"valueQuantity": {
					"value": 24,
					"unit": "mmol/L",
					"system": "http://unitsofmeasure.org/",
					"code": "mmol/L"
				}
			},
			"search": {
				"mode": "match"
			}

		}, {
			"fullUrl": "https://r3.smarthealthit.org/Observation/e3fd8be3-7e87-4f84-a236-00535b5819d3",
			"resource": {
				"resourceType": "Observation",
				"id": "e3fd8be3-7e87-4f84-a236-00535b5819d3",
				"meta": {
					"versionId": "2",
					"lastUpdated": "2018-04-25T03:23:31.117-04:00",
					"profile": [
						"http://standardhealthrecord.org/fhir/StructureDefinition/shr-observation-Observation"
					],
					"tag": [{
							"system": "https://smarthealthit.org/tags",
							"code": "synthea-7-2017"
						}
					]
				},
				"status": "final",
				"category": [{
						"coding": [{
								"system": "http://hl7.org/fhir/observation-category",
								"code": "laboratory"
							}
						]
					}
				],
				"code": {
					"coding": [{
							"system": "http://loinc.org",
							"code": "2339-0",
							"display": "Glucose"
						}
					],
					"text": "Glucose"
				},
				"subject": {
					"reference": "Patient/3b5064a0-e23c-458c-897e-3491a494eb32"
				},
				"context": {
					"reference": "Encounter/cf5ba549-78b8-4f93-b9b5-1d5f73f6a6d1"
				},
				"effectiveDateTime": "2008-03-07T23:13:53-05:00",
				"issued": "2008-03-07T23:13:53-05:00",
				"valueQuantity": {
					"value": 67,
					"unit": "mg/dL",
					"system": "http://unitsofmeasure.org/",
					"code": "mg/dL"
				}
			},
			"search": {
				"mode": "match"
			}
		}
	]
}